title:               Fionn's Digital Garden
url:                 https://fionnd.github.io/garden
baseurl:             /garden

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Fionn Delahunty
  url:               fionnd.github.io
  email:             fionnd@pm.me

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
